---
- hosts: all
  sudo: yes
  remote_user: ubuntu
  tasks:
    - name: Update all packages
      apt: update_cache=yes

    - name: Install Vim
      apt: name=vim state=present

    - name: Install Git
      apt: pkg=git state=installed
      
    - name: Install ufw
      apt: pkg=ufw state=installed
      tags: ufw

    - name: Enable ufw
      ufw: state=reset

    - name: Deny ufw from  all access
      ufw: policy=deny direction=incoming
      tags: ufw

    - name: Allow from ssh connection
      ufw: policy=allow port=22
      tags: ufw

    - name: Allow from HTTP request
      ufw: policy=allow port=80
      tags: ufw

    - name: Enable ufw
      ufw: state=enabled

    - name: Install pip
      apt: pkg=python-pip state=installed

    - name: Make web directory
      command: mkdir -p /var/www/piyokkuma

    - name: Install pyramid
      pip: name=pyramid

    - name: Install pyramid_mako
      pip: name=pyramid_mako

    - name: Install zope.interface
      pip: name=zope.interface

    - name: Install zope.deprecation
      pip: name=zope.deprecation

## -- Current Memo --
## 以下何度か試してみる
## 上記の後に
##    sudo pip upgrade zope.interface
## したらうまくできた。が謎だ。
